config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dgmaths9/gales:
      branch: main
      repo: https://gitlab.com/dgmaths9/gales
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dgmaths9/gales git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-silver-dane.sh
        container: qc.acc_pretty-rust-giraffe
  QC.Doc:
    repos:
      gitlab.com/dgmaths9/gales find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lilac-bandicoot.sh
        container: qc.doc_sleepy-jade-indri
      gitlab.com/dgmaths9/gales git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-auburn-labradoodle.sh
        container: qc.doc_seedy-salmon-fox
      gitlab.com/dgmaths9/gales markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-celadon-hyena.sh
        container: qc.doc_wimpy-cerulean-javanese
  QC.Lic:
    repos:
      gitlab.com/dgmaths9/gales licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-asparagus-hummingbird.sh
        container: qc.lic_tacky-taupe-stoat
  QC.Sec:
    repos:
      gitlab.com/dgmaths9/gales bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-lemon-snake.sh
        container: qc.sec_snoopy-jade-toucan
  QC.Sty:
    repos:
      gitlab.com/dgmaths9/gales flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-razzmatazz-macaw.sh
        container: qc.sty_gummy-harlequin-scorpion
  QC.Ver:
    repos:
      gitlab.com/dgmaths9/gales get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-brass-mayfly.sh
        container: qc.ver_skinny-azure-bear
timeout: 5400
